-- ADD NEW COLUMNS FOR AMBASSADOR SUPPORT
ALTER TABLE IF EXISTS staff ADD COLUMN IF NOT EXISTS auth_id UUID;
ALTER TABLE IF EXISTS staff ADD COLUMN IF NOT EXISTS is_first_login BOOLEAN;
ALTER TABLE IF EXISTS staff ADD COLUMN IF NOT EXISTS incentive_mode TEXT DEFAULT 'earn';
ALTER TABLE IF EXISTS staff ADD COLUMN IF NOT EXISTS charity_pot NUMERIC DEFAULT 0;
ALTER TABLE IF EXISTS staff ADD COLUMN IF NOT EXISTS charities JSONB DEFAULT '[]'::jsonb;
